os:
    - linux

sudo: required
dist: trusty

language: c

services:
    - docker

install:
    - echo "FROM ${DOCKER_IMAGE}" > Dockerfile
    - docker-compose build

script:
    - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests

env:
    - DOCKER_IMAGE=pathman/pg95_clang_check_code
    - DOCKER_IMAGE=pathman/pg95_pathman_tests
    - DOCKER_IMAGE=pathman/pg96_clang_check_code
    - DOCKER_IMAGE=pathman/pg96_pathman_tests
    - DOCKER_IMAGE=pathman/pg10_clang_check_code
    - DOCKER_IMAGE=pathman/pg10_pathman_tests
    - DOCKER_IMAGE=pathman/pg10_ca_clang_check_code
    - DOCKER_IMAGE=pathman/pg10_ca_pathman_tests
